### ISSUE TITLE
Dealing with Array/List type of inputs

### ISSUE THREAD

**Issue by rinn7e** [fpco/halogen-form#2]
First of all, thanks for this great library. One thing that I have problem with is doing dynamic checkboxes. I am trying to find way to create the formbuilder so that the result it return would be:
```
{ name :: String
, desc :: String
, categories :: Array String
}
```

Another approach would be passing string as record name field so that we can do
```
( map {"name": _} Form.required errors (Form.text Nothing)
 <|*> map {"desc": _} Form.required errors (Form.text Nothing)
 <|*> (mapM_ (\x -> map {"x": _} Form.required errors (Form.checkbox Nothing)) ["category1", "category2"])
)
```
which should return
```
{ name :: String
, desc :: String
, category1 :: String
, category2 :: String
}
```
But I'm still not sure how to turn that `{category1 :: String, category2 :: String} into {categories :: Array String}`

Or there maybe other approach all together, hope someone shed some light on this.

**Comment by chrisdone** [comment]
Re-read carefully the example here:

https://github.com/fpco/halogen-form#building-records

```haskell
person ::
  forall h.
    FormBuilder
      FormError
      (Array (HH.HTML h (Query Unit)))
      { name :: String, age :: Number}
person =
  map {name: _} (Form.required (Form.text errors Nothing)) <|*>
  map {age: _} (Form.required (Form.number errors Nothing)) <*
  submitInput "Submit!"
```

To build an array of form parts, use `traverse`:


```haskell
traverse (\cat -> Form.text errors Nothing) ["a","b"]
```

Just put the `map {"categories":_}` wrapping around the traverse call.

```haskell
map {"categories":_} (traverse (\cat -> Form.text errors Nothing) ["a","b"])
```

How is your `checkbox` defined?

**Comment by chrisdone** [comment]
Ideally, you'll have:

```haskell
checkbox ::
     forall e a.
     Boolean
  -> FormBuilder e (Array (HH.HTML a (Query Unit))) Boolean
```

If you want to build a list of strings, they should be mapped back to the strings, e.g.

```haskell
traverse
   (\category ->
       map {title: category.title, value: _} 
           (wrap (\_err checkboxHtml -> [HH.text category.title] <> checkboxHtml])
                 (Form.checkbox category.value))
   [{ title: "Jazz", value: false }, { title: "Rock", value: true }]
```

that will give you `Array { title :: String, value :: Boolean }`, and
you can use `mapMaybe` to just get the titles that are `true`, if
desired.

**Comment by chrisdone** [comment]
Or more generally:
```haskell
checkbox ::  
  forall e a.  { on :: a, off :: a } -> FormBuilder e (Array (HH.HTML a (Query Unit))) a
```
Then one could use sum types more easily. :man_shrugging:

**Comment by rinn7e** [comment]
Thanks very much, Chris. The code snippet on the `traverse` really helps me understanding on building the form so that it returns array. I have tweaked checkbox a little bit to my own requirement. Everything works as expected now.

**Comment by BSFYBCXH** [comment]
nice
